# Data path. adjust them!
common:
    image_file: "/home/ycj/data/calib/image/0.png"
    pcd_file: "/home/ycj/data/calib/pcd/0.pcd"
    result_file: "/home/ycj/data/calib/extrinsic.txt"

# Camera Parameters. Adjust them!
camera:
    camera_matrix: [653.47554,   0.     , 950.58212,
           0.     , 595.02553, 669.88204,
           0.     ,   0.     ,   1.    ]
    dist_coeffs: [-0.098478, 0.023177, -0.000431, -0.000113, 0.000000]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/robot/campus/ws/src/livox_camera_calib-master/config/config_indoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
